name: Test model solution with GAMS

env:
  GAMS_MAJOR: 29
  GAMS_MINOR: 1
  GAMS_MAINT: 0

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GAMS
        run: |
          cd ~
          wget -nv https://d37drm4t2jghv5.cloudfront.net/distributions/${GAMS_MAJOR}.${$GAMS_MINOR}.${GAMS_MAINT}/linux/linux_x64_64_sfx.exe
          chmod 755 linux_x64_64_sfx.exe
          ./linux_x64_64_sfx.exe
          echo "~/gams${GAMS_MAJOR}.${$GAMS_MINOR}_linux_x64_64_sfx" >> $GITHUB_PATH
      - name: Run GAMS
        run: |
          for gmsfile in *.gms
          do
            gams "${gmsfile}" lo=4 gdx="${gmsfile/.gms/}"
            cat "${gmsfile/gms/lst}"
          done
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: gams-results-files
          path: |
            ./*.lst
            ./*.log
            ./*.gdx
