name: Test model solution with GAMS

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GAMS
        run: |
          cd ~
          wget -nv https://d37drm4t2jghv5.cloudfront.net/distributions/29.1.0/linux/linux_x64_64_sfx.exe
          chmod 755 linux_x64_64_sfx.exe
          ./linux_x64_64_sfx.exe
          echo "~/gams29.1_linux_x64_64_sfx" >> $GITHUB_PATH
      - name: Run GAMS
        run: |
          for gmsfile in *.gms
          do
            gams ${gmsfile} lo=4
            cat ${gmsfile/gms/lst}
          done
      - name: Archive results (lst)
        uses: actions/upload-artifact@v2
        with:
          name: lst-files
          path: ./*.lst
      - name: Archive results (log)
        uses: actions/upload-artifact@v2
        with:
          name: log-files
          path: ./*.log
      - name: Archive results (gdx)
        uses: actions/upload-artifact@v2
        with:
          name: gdx-files
          path: ./*.gdx
  
